baseurl = "/"
publishDir = "public"
title = "Homer's Academic Blog"
author = "Homer White"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "Homer's Academic Blog"

[taxonomies]
  tag = "tags"
  category = "categories"
  aggregator = "aggregators"
  
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/homerhanumat"
    weight = 3
[[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 4
